## Data Preprocessing

It is the step where we perform the following steps -
    - Getting Dataset  
    - Importing the libraries and the dataset  
    - Finding missing values  
    - Encoding categorial data  
    - Split into training and test dataset  
    - Feature Scaling  

### Importing the libraries of Pandas and Numpy

In [2]:
import pandas as pd
import numpy as np

Importing the dataset

In [3]:
df = pd.read_csv("../datasets/employees.csv")
df.head()

EMPLOYEE_ID FIRST_NAME  LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald   OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas      Grant    DGRANT  650.507.9844  13-JAN-08   
2          200   Jennifer     Whalen   JWHALEN  515.123.4444  17-SEP-03   
3          201    Michael  Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4          202        Pat        Fay      PFAY  603.123.6666  17-AUG-05   

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600             -         124             50  
1  SH_CLERK    2600             -         124             50  
2   AD_ASST    4400             -         101             10  
3    MK_MAN   13000             -         100             20  
4    MK_REP    6000             -         201             20

separate out the independent and dependent variables in the form of arrays

In [13]:
x = df[['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME' , 'EMAIL', 'PHONE_NUMBER', 'JOB_ID' , 'HIRE_DATE','SALARY']]

we have to make the array of independent variables

In [14]:
y = x.values

handling the missing values in the data

In [15]:
from sklearn.impute import SimpleImputer

In [16]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [21]:
imput = imputer.fit(y[:,7:8])

In [24]:
y[:,7:8] = imput.transform(y[:,7:8])

In [25]:
y

array([[198, 'Donald', 'OConnell', 'DOCONNEL', '650.507.9833',
        'SH_CLERK', '21-JUN-07', 2600.0],
       [199, 'Douglas', 'Grant', 'DGRANT', '650.507.9844', 'SH_CLERK',
        '13-JAN-08', 2600.0],
       [200, 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444', 'AD_ASST',
        '17-SEP-03', 4400.0],
       [201, 'Michael', 'Hartstein', 'MHARTSTE', '515.123.5555',
        'MK_MAN', '17-FEB-04', 13000.0],
       [202, 'Pat', 'Fay', 'PFAY', '603.123.6666', 'MK_REP', '17-AUG-05',
        6000.0],
       [203, 'Susan', 'Mavris', 'SMAVRIS', '515.123.7777', 'HR_REP',
        '07-JUN-02', 6500.0],
       [204, 'Hermann', 'Baer', 'HBAER', '515.123.8888', 'PR_REP',
        '07-JUN-02', 10000.0],
       [205, 'Shelley', 'Higgins', 'SHIGGINS', '515.123.8080', 'AC_MGR',
        '07-JUN-02', 12008.0],
       [206, 'William', 'Gietz', 'WGIETZ', '515.123.8181', 'AC_ACCOUNT',
        '07-JUN-02', 8300.0],
       [100, 'Steven', 'King', 'SKING', '515.123.4567', 'AD_PRES',
        '17-JUN-03', 24

### Encoding categorial data 

categorial data means which have labels. Encoding categorial data into numericals.  
This is because most of the algorithm data can't work with categorial data. Some of algorithm like decision
tree can work with these data but many work with only numeric columns

In [26]:
from sklearn.preprocessing import LabelEncoder

this library will convert categorial data into digits and numerical

In [27]:
label_encoder_y = LabelEncoder()

In [35]:
y[:,1] = label_encoder_y.fit_transform(y[:,1])

In [36]:
y

array([[198, 7, 'OConnell', 'DOCONNEL', '650.507.9833', 'SH_CLERK',
        '21-JUN-07', 2600.0],
       [199, 8, 'Grant', 'DGRANT', '650.507.9844', 'SH_CLERK',
        '13-JAN-08', 2600.0],
       [200, 16, 'Whalen', 'JWHALEN', '515.123.4444', 'AD_ASST',
        '17-SEP-03', 4400.0],
       [201, 28, 'Hartstein', 'MHARTSTE', '515.123.5555', 'MK_MAN',
        '17-FEB-04', 13000.0],
       [202, 32, 'Fay', 'PFAY', '603.123.6666', 'MK_REP', '17-AUG-05',
        6000.0],
       [203, 41, 'Mavris', 'SMAVRIS', '515.123.7777', 'HR_REP',
        '07-JUN-02', 6500.0],
       [204, 11, 'Baer', 'HBAER', '515.123.8888', 'PR_REP', '07-JUN-02',
        10000.0],
       [205, 36, 'Higgins', 'SHIGGINS', '515.123.8080', 'AC_MGR',
        '07-JUN-02', 12008.0],
       [206, 44, 'Gietz', 'WGIETZ', '515.123.8181', 'AC_ACCOUNT',
        '07-JUN-02', 8300.0],
       [100, 40, 'King', 'SKING', '515.123.4567', 'AD_PRES', '17-JUN-03',
        24000.0],
       [101, 31, 'Kochhar', 'NKOCHHAR', '515.123.4568', '

we do dummy encoding to prevent any error due to correlation between the data

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
one_hot_encoder = OneHotEncoder()

In [40]:
z = one_hot_encoder.fit_transform(df.FIRST_NAME.values.reshape(-1,1)).toarray

In [41]:
z

<bound method _cs_matrix.toarray of <50x45 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>>

## training and testing data

divide your dataset into a training and testing data

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

the test size is 20 percent of the datasize. you can take any other value.  

random state - it means that fix value everytime. same result

In [44]:
x_train

EMPLOYEE_ID   FIRST_NAME    LAST_NAME     EMAIL  PHONE_NUMBER      JOB_ID  \
33          124        Kevin      Mourgos  KMOURGOS  650.123.5234      ST_MAN   
35          126        Irene  Mikkilineni  IMIKKILI  650.124.1224    ST_CLERK   
26          117        Sigal       Tobias   STOBIAS  515.127.4564    PU_CLERK   
34          125        Julia        Nayer    JNAYER  650.124.1214    ST_CLERK   
18          109       Daniel       Faviet   DFAVIET  515.124.4169  FI_ACCOUNT   
7           205      Shelley      Higgins  SHIGGINS  515.123.8080      AC_MGR   
14          105        David       Austin   DAUSTIN  590.423.4569     IT_PROG   
45          136        Hazel   Philtanker  HPHILTAN  650.127.1634    ST_CLERK   
48          139         John          Seo      JSEO  650.121.2019    ST_CLERK   
29          120      Matthew        Weiss    MWEISS  650.123.1234      ST_MAN   
15          106        Valli    Pataballa  VPATABAL  590.423.4560     IT_PROG   
30          121         Adam        Fripp    AFRIPP  650.123.2234      ST_MAN   
32          123       Shanta      Vollman  SVOLLMAN  650.123.4234      ST_MAN   
16          107        Diana      Lorentz  DLORENTZ  590.423.5567     IT_PROG   
42          133        Jason       Mallin   JMALLIN  650.127.1934    ST_CLERK   
20          111       Ismael      Sciarra  ISCIARRA  515.124.4369  FI_ACCOUNT   
43          134      Michael       Rogers   MROGERS  650.127.1834    ST_CLERK   
8           206      William        Gietz    WGIETZ  515.123.8181  AC_ACCOUNT   
13          104        Bruce        Ernst    BERNST  590.423.4568     IT_PROG   
25          116       Shelli        Baida    SBAIDA  515.127.4563    PU_CLERK   
5           203        Susan       Mavris   SMAVRIS  515.123.7777      HR_REP   
17          108        Nancy    Greenberg  NGREENBE  515.124.4569      FI_MGR   
40          131        James       Marlow   JAMRLOW  650.124.7234    ST_CLERK   
49          140       Joshua        Patel    JPATEL  650.121.1834    ST_CLERK   
1           199      Douglas        Grant    DGRANT  650.507.9844    SH_CLERK   
12          103    Alexander       Hunold   AHUNOLD  590.423.4567     IT_PROG   
37          128       Steven       Markle   SMARKLE  650.124.1434    ST_CLERK   
24          115    Alexander         Khoo     AKHOO  515.127.4562    PU_CLERK   
6           204      Hermann         Baer     HBAER  515.123.8888      PR_REP   
23          114          Den     Raphaely  DRAPHEAL  515.127.4561      PU_MAN   
36          127        James       Landry   JLANDRY  650.124.1334    ST_CLERK   
21          112  Jose Manuel        Urman   JMURMAN  515.124.4469  FI_ACCOUNT   
19          110         John         Chen     JCHEN  515.124.4269  FI_ACCOUNT   
9           100       Steven         King     SKING  515.123.4567     AD_PRES   
39          130        Mozhe     Atkinson  MATKINSO  650.124.6234    ST_CLERK   
46          137       Renske       Ladwig   RLADWIG  650.121.1234    ST_CLERK   
3           201      Michael    Hartstein  MHARTSTE  515.123.5555      MK_MAN   
0           198       Donald     OConnell  DOCONNEL  650.507.9833    SH_CLERK   
47          138      Stephen       Stiles   SSTILES  650.121.2034    ST_CLERK   
44          135           Ki          Gee      KGEE  650.127.1734    ST_CLERK   

    HIRE_DATE  SALARY  
33  16-NOV-07    5800  
35  28-SEP-06    2700  
26  24-JUL-05    2800  
34  16-JUL-05    3200  
18  16-AUG-02    9000  
7   07-JUN-02   12008  
14  25-JUN-05    4800  
45  06-FEB-08    2200  
48  12-FEB-06    2700  
29  18-JUL-04    8000  
15  05-FEB-06    4800  
30  10-APR-05    8200  
32  10-OCT-05    6500  
16  07-FEB-07    4200  
42  14-JUN-04    3300  
20  30-SEP-05    7700  
43  26-AUG-06    2900  
8   07-JUN-02    8300  
13  21-MAY-07    6000  
25  24-DEC-05    2900  
5   07-JUN-02    6500  
17  17-AUG-02   12008  
40  16-FEB-05    2500  
49  06-APR-06    2500  
1   13-JAN-08    2600  
12  03-JAN-06    9000  
37  08-MAR-08    2200  
24  18-MAY

In [45]:
y_test

array([[119, 21, 'Colmenares', 'KCOLMENA', '515.127.4566', 'PU_CLERK',
        '10-AUG-07', 2500.0],
       [102, 25, 'De Haan', 'LDEHAAN', '515.123.4569', 'AD_VP',
        '13-JAN-01', 17000.0],
       [101, 31, 'Kochhar', 'NKOCHHAR', '515.123.4568', 'AD_VP',
        '21-SEP-05', 17000.0],
       [132, 42, 'Olson', 'TJOLSON', '650.124.8234', 'ST_CLERK',
        '10-APR-07', 2100.0],
       [200, 16, 'Whalen', 'JWHALEN', '515.123.4444', 'AD_ASST',
        '17-SEP-03', 4400.0],
       [118, 9, 'Himuro', 'GHIMURO', '515.127.4565', 'PU_CLERK',
        '15-NOV-06', 2600.0],
       [129, 24, 'Bissot', 'LBISSOT', '650.124.5234', 'ST_CLERK',
        '20-AUG-05', 3300.0],
       [122, 33, 'Kaufling', 'PKAUFLIN', '650.123.3234', 'ST_MAN',
        '01-MAY-03', 7900.0],
       [113, 26, 'Popp', 'LPOPP', '515.124.4567', 'FI_ACCOUNT',
        '07-DEC-07', 6900.0],
       [202, 32, 'Fay', 'PFAY', '603.123.6666', 'MK_REP', '17-AUG-05',
        6000.0]], dtype=object)

## feature scaling

it is the last step of our data preprocessing. If we have any data which is way beyond the other data.
we use feature scaling.

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc_x = StandardScaler()

In [50]:
# x_train =sc_x.fit_transform(x_train)

# can be used to only numerical values

similarly do form x_test